services:
  app:
    image: 950756301515.dkr.ecr.ap-northeast-2.amazonaws.com/community-portfolio:latest
    container_name: community-app

    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"

    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"
      REFRESH_COOKIE_SECURE: "${REFRESH_COOKIE_SECURE}"
      REFRESH_COOKIE_SAME_SITE: "${REFRESH_COOKIE_SAME_SITE}"
      REFRESH_COOKIE_DOMAIN: "${REFRESH_COOKIE_DOMAIN}"
      # Admin seeding (optional): set to enable Flyway V10 admin seed
      ADMIN_EMAIL: "${ADMIN_EMAIL:-}"
      ADMIN_USERNAME: "${ADMIN_USERNAME:-}"
      ADMIN_PASSWORD_HASH: "${ADMIN_PASSWORD_HASH:-}"
      S3_BUCKET: "${S3_BUCKET}"
      SERVER_PORT: "${SERVER_PORT:-8080}"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -XX:+UseContainerSupport"

    volumes:
      - /opt/community-portfolio/uploads:/app/uploads

    tmpfs:
      - /tmp

    restart: unless-stopped
    stop_grace_period: 30s
    security_opt:
      - no-new-privileges:true
    read_only: true

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${SERVER_PORT:-8080}/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
